version: "3.9"
services:
  test-lc-api:
    image: warching/langchain-agent-api
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./htmls:/app/htmls
    networks:
      - langchain-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  openai-teams-bot:
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    image: warching/openai-teams-bot:langchain
    ports:
      - "3978:3978"
    env_file:
      - .env
    networks:
      - langchain-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  langchain-network: