version: "3.9"
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres #postgres
        POSTGRES_PASSWORD: postgres #1234
        PGDATA: /var/lib/postgresql/data
    volumes:
        - ./db-data:/var/lib/postgresql/data
        - ./init-config/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    ports:
        - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  langchain-network: