version: "3.9"
services:
  test-lc-api:
    image: warching/langchain-agent-api
    ports:
      - "8000:80"
    # command:
    #   - /bin/sh
    #   - -c
    #   - |
    #       sleep 3600
    env_file:
      - .env
    volumes:
      - ./markdowns:/app/markdowns
      - ./urls:/app/urls
      - ./htmls:/app/htmls
      - ./pdfs:/app/pdfs
      - ./txts:/app/txts
      - ./csvs:/app/csvs
    networks:
      - langchain-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  openai-teams-bot:
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    image: warching/openai-teams-bot:langchain
    ports:
      - "3978:3978"
    env_file:
      - .env
    networks:
      - langchain-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  langchain-network: