### Test CSV Tool
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "Any existing vulnerabilities",
    "id": "1"
}

### Test HTML Tool
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "How to do MR in GitLab?",
    "id": "1"
}

### Test Markdown Tool
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "How to config pipeline in GitLab?",
    "id": "1"
}

### Test PDF Tool
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "How to use GitLab share runner?",
    "id": "1"
}

### Test Txt Tool
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "Do GitLab has container registry?",
    "id": "1"
}

### Custom Test
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "你好我是Ada",
    "id": "ada"
}

### Custom Test
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "有沒有科學的書推薦？",
    "id": "ada"
}

### Custom Test
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "那有沒有哈利波特？",
    "id": "ada"
}

### Custom Test
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "我之前問過什麼書？",
    "id": "ada"
}

### Custom Test
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "我叫什麼名字？",
    "id": "ada"
}

### Custom Test
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "What makes GitLab better than GitHub?",
    "id": "ada"
}

### Custom Test
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "Answer in English",
    "id": "ada"
}