### Test CSV Tool
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "Any existing vulnerabilities",
    "id": "1"
}

### Test HTML Tool
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "How to do MR in GitLab?",
    "id": "1"
}

### Test Markdown Tool
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "How to config pipeline in GitLab?",
    "id": "1"
}

### Test PDF Tool
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "How to use GitLab share runner?",
    "id": "1"
}

### Test Txt Tool
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "Do GitLab has container registry?",
    "id": "1"
}

### Test Memory
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "Hi my name is Ada",
    "id": "1"
}

### Test Memory
POST http://127.0.0.1:8000/run
content-type: application/json

{
    "text": "What is my name?",
    "id": "1"
}

### Test Zapier
POST http://127.0.0.1/run
content-type: application/json

{
    "text": "Summarize the last gmail I received regarding AI flow solution, then create a card in Trello with the summarized content in 10 words as title",
    "id": "3"
}

### Test Zapier
POST http://127.0.0.1/run
content-type: application/json

{
    "text": "Find the last gmail I received regarding Google Cloud Platform",
    "id": "2"
}